'use client'
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import { usePathname } from "next/navigation";
import { useRouter } from "next/navigation";
import Player from "@/components/Player";
import { useState } from "react";
import BottomNav from "@/components/BottomNav";
import Header from "@/components/Header";
import { ClientAuthProvider } from "@/components/ClientAuthProvider";
import ProtectedRoute from "@/components/ProtectedRoute";
import { PlayerProvider } from "@/context/PlayerContext";
import { MiniPlayer } from '../components/MiniPlayer';
import { AnimatePresence } from 'framer-motion';
import { ProfileProvider } from "@/context/ProfileContext";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
    const [showSidebar,setShowSidebar]=useState(false)
  
const pathname = usePathname();
  const isNowPlayingPage = pathname === '/now-playing';
  const router = useRouter()
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased `}
      >
      <ClientAuthProvider>
      <ProfileProvider>
      <PlayerProvider>

        <div className="bg-white min-h-screen relative text-black">
      {/* Header */}
      <Header showSidebar={showSidebar} setShowSidebar={setShowSidebar} />
      
      {/* Main Content */}
      <main className="p-4">

        {children}

        <AnimatePresence>
              {!isNowPlayingPage && <MiniPlayer />}
            </AnimatePresence>
      </main>
      
      {/* Mini Player (when not in full player view) */}
      {/* {pathname !== 'now-playing' && (
        <Player  />
      )} */}
      
      {/* Bottom Navigation */}
      <BottomNav />
    </div>
      </PlayerProvider>
      </ProfileProvider>
      </ClientAuthProvider>
      </body>
    </html>
  );
}
