'use client'
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import { usePathname } from "next/navigation";
import { useRouter } from "next/navigation";
import Player from "@/components/Player";
import { useState } from "react";
import BottomNav from "@/components/BottomNav";
import Header from "@/components/Header";
import Sidebar from "@/components/Sidebar";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
    const [isPlaying, setIsPlaying] = useState(false);
    const [showSidebar,setShowSidebar]=useState(false)
  
  const pathname = usePathname()
  const router = useRouter()
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased `}
      >
      <div className="bg-white min-h-screen text-black">
      <div className="flex">
        {/* Sidebar for desktop */}
        <Sidebar showSidebar={showSidebar} setShowSidebar={setShowSidebar} />

        {/* Main content area */}
        <div className="flex-1">
          {/* Header */}
          <Header showSidebar={showSidebar} setShowSidebar={setShowSidebar} />
          
          {/* Main content area */}
          <main className="p-4 lg:p-6">
            {children}
          </main>
        </div>
      </div>
      
      {/* Bottom Navigation (Mobile only) */}
      <BottomNav />
      
      {/* Mini Player */}
      {/* {showMiniPlayer && <MiniPlayer />} */}
      
      {/* Overlay when sidebar is open on mobile */}
      {showSidebar && (
        <div 
          className="fixed inset-0 bg-black/30 z-10 lg:hidden"
          onClick={() => setShowSidebar(false)}
        ></div>
      )}
    </div>
      </body>
    </html>
  );
}
  // {/* {children} */}
  //       <div className="bg-white min-h-screen relative text-black">
  //     {/* Header */}
  //     <Header showSidebar={showSidebar} setShowSidebar={setShowSidebar} />
      
  //     {/* Main Content */}
  //     <main className="p-4">
  //       {children}
  //     </main>
      
  //     {/* Mini Player (when not in full player view) */}
  //     {pathname !== 'player' && (
  //       <Player isPlaying={isPlaying} setIsPlaying={setIsPlaying} />
  //     )}
      
  //     {/* Bottom Navigation */}
  //     <BottomNav />
  //   </div>